export interface SamplePair {
  slug: string
  title: string
  beforeLabel: string
  afterLabel: string
  /** Photographer of the source photo (Unsplash). Variants are generated by scripts/make-samples.mjs. */
  photographer: string
}

export const SAMPLE_PAIRS: SamplePair[] = [
  { slug: 'colorize', title: 'Colorize', beforeLabel: 'B&W', afterLabel: 'Color', photographer: 'Natalie Sierra' },
  { slug: 'mood', title: 'Mood', beforeLabel: 'Day', afterLabel: 'Golden hour', photographer: 'Adriel Kloppenburg' },
  { slug: 'upscale', title: 'Upscale', beforeLabel: 'Low-res', afterLabel: 'Crisp', photographer: 'Uran Wang' },
  { slug: 'grade', title: 'Color grade', beforeLabel: 'Flat', afterLabel: 'Graded', photographer: 'Metin Ozer' },
  { slug: 'sharpen', title: 'Sharpen', beforeLabel: 'Blurry', afterLabel: 'Sharp', photographer: 'Luca Iaconelli' },
  { slug: 'hdr', title: 'HDR', beforeLabel: 'Dull', afterLabel: 'Dramatic', photographer: 'Eric Carlson' },
  { slug: 'denoise', title: 'Denoise', beforeLabel: 'Noisy', afterLabel: 'Clean', photographer: 'Uran Wang' },
  { slug: 'exposure', title: 'Exposure', beforeLabel: 'Overexposed', afterLabel: 'Balanced', photographer: 'Luca Iaconelli' },
]

// import.meta.env is undefined outside Vite (plain node), so fall back to the root.
const BASE = import.meta.env?.BASE_URL ?? '/'

export const sampleUrl = (slug: string, which: 'before' | 'after') => `${BASE}samples/${slug}-${which}.webp`
